---
- name: VLAN
  hosts: all
  gather_facts: true

  tasks:
    - name: install software on CentOS
      ansible.builtin.yum:
        name:
          - vim
          - traceroute
          - tcpdump
          - net-tools
        state: present
        update_cache: true
      when: (ansible_os_family == "RedHat")
      
      #Установка приложений на Debian-based системах
    - name: install software on Debian-based
      ansible.builtin.apt:
        name: 
          - vim
          - traceroute
          - tcpdump
          - net-tools
        state: present
        update_cache: true
      when: (ansible_os_family == "Debian")

- name:  config interfaces for client and servers
  hosts: Servers,Clients
  gather_facts: true
    
  tasks:
    - name: config interfaces for client and servers
      ansible.builtin.template:
        src: ifcfg-vlan.j2
        dest: '/etc/sysconfig/network-scripts/ifcfg-vlan{{vlan_id}}'
        owner: root
        group: root
        mode: 0644
      when: ansible_os_family == "RedHat"

    - name: restart network for vlan1
      service:
        name: network.service
        state: restarted
      when: ansible_os_family == "RedHat"

    - name: config interfaces for client and servers
      ansible.builtin.template:
        src: 60-cloud-init.yaml.j2
        dest: '/etc/netplan/60-cloud-init.yaml'
        owner: root
        group: root
        mode: 0644
      when: 
        - ansible_os_family == "Debian"

    - name: apply set up vlan2
      shell: netplan apply
      when: ansible_os_family == "Debian"

- name: set up bond0
  hosts: inetRouter,centralRouter
  become: yes
  tasks:
  - name: set up ifcfg-bond0
    ansible.builtin.template:
      src: ifcfg-bond0.j2
      dest: /etc/sysconfig/network-scripts/ifcfg-bond0
      owner: root
      group: root
      mode: 0644
  
  - name: set up eth1,eth2
    ansible.builtin.template: 
      src: "{{ item }}" 
      dest: /etc/sysconfig/network-scripts/
      owner: root
      group: root
      mode: 0644
    with_items:
      - ifcfg-eth1
      - ifcfg-eth2
  #Перезагрузка хостов 
  - name: restart hosts for bond0
    ansible.builtin.reboot:
      reboot_timeout: 3600
